import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ActivityIndicator,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { DocumentGenerationJob } from '../../types/documentTemplate';

interface GenerationHistoryViewProps {
  history: DocumentGenerationJob[];
  loading?: boolean;
  onRefresh: () => void;
  isDark?: boolean;
}

export const GenerationHistoryView: React.FC<GenerationHistoryViewProps> = ({
  history,
  loading = false,
  onRefresh,
  isDark = false,
}) => {
  const textColor = isDark ? '#F9FAFB' : '#111827';
  const subtextColor = isDark ? '#9CA3AF' : '#4B5563';
  const tableBg = isDark ? '#18202F' : '#FFFFFF';
  const borderColor = isDark ? '#374151' : '#E2E8F0';
  const headerBg = isDark ? '#1F2937' : '#F8FAFC';

  const formatInr = (val: number) => '₹' + Number(val || 0).toLocaleString('en-IN');
  const formatDate = (isoStr: string) => {
    try {
      const d = new Date(isoStr);
      return d.toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
    } catch {
      return isoStr;
    }
  };

  return (
    <View style={[styles.container, { backgroundColor: tableBg, borderColor }]}>
      <View style={[styles.topBar, { borderBottomColor: borderColor, backgroundColor: headerBg }]}>
        <div>
          <div style={{ fontSize: 16, fontWeight: 700, color: textColor }}>Document Generation Audit & History</div>
          <div style={{ fontSize: 12, color: subtextColor }}>
            Permanent record of all fee notices, slips, and exports generated by accounts staff
          </div>
        </div>
        <TouchableOpacity style={styles.refreshBtn} onPress={onRefresh}>
          <Ionicons name="refresh" size={16} color={textColor} />
          <Text style={[styles.refreshText, { color: textColor }]}>Refresh</Text>
        </TouchableOpacity>
      </View>

      {loading ? (
        <View style={styles.loadingBox}>
          <ActivityIndicator size="large" color="#3B82F6" />
          <Text style={[styles.loadingText, { color: subtextColor }]}>Loading audit logs...</Text>
        </View>
      ) : history.length === 0 ? (
        <View style={styles.emptyBox}>
          <Ionicons name="time-outline" size={44} color="#94A3B8" />
          <Text style={[styles.emptyTitle, { color: textColor }]}>No generation history recorded yet</Text>
          <Text style={[styles.emptyDesc, { color: subtextColor }]}>
            When you generate fee due slips, batch jobs and audit records will appear here.
          </Text>
        </View>
      ) : (
        <div style={{ overflowX: 'auto', width: '100%' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              <tr style={{ backgroundColor: headerBg, borderBottom: `1px solid ${borderColor}`, color: subtextColor }}>
                <th style={{ padding: '10px 14px', textAlign: 'left', fontWeight: 600 }}>Date & Time</th>
                <th style={{ padding: '10px 14px', textAlign: 'left', fontWeight: 600 }}>Generated By</th>
                <th style={{ padding: '10px 14px', textAlign: 'left', fontWeight: 600 }}>Template Used</th>
                <th style={{ padding: '10px 14px', textAlign: 'center', fontWeight: 600 }}>Students</th>
                <th style={{ padding: '10px 14px', textAlign: 'right', fontWeight: 600 }}>Total Due Amount</th>
                <th style={{ padding: '10px 14px', textAlign: 'center', fontWeight: 600 }}>Format</th>
                <th style={{ padding: '10px 14px', textAlign: 'center', fontWeight: 600 }}>Status</th>
              </tr>
            </thead>
            <tbody>
              {history.map((job, idx) => (
                <tr
                  key={job.id}
                  style={{
                    borderBottom: `1px solid ${borderColor}`,
                    backgroundColor: idx % 2 === 1 ? headerBg : 'transparent',
                  }}
                >
                  <td style={{ padding: '10px 14px', color: textColor, fontWeight: 500 }}>
                    {formatDate(job.created_at)}
                  </td>
                  <td style={{ padding: '10px 14px', color: textColor }}>
                    {job.created_by_name || 'Accounts Staff'}
                  </td>
                  <td style={{ padding: '10px 14px', color: textColor, fontWeight: 600 }}>
                    {job.template_name || 'Standard Fee Due Slip'}
                  </td>
                  <td style={{ padding: '10px 14px', textAlign: 'center', fontWeight: 700, color: textColor }}>
                    {job.student_count}
                  </td>
                  <td style={{ padding: '10px 14px', textAlign: 'right', fontVariantNumeric: 'tabular-nums', fontWeight: 700, color: '#DC2626' }}>
                    {formatInr(job.total_due_amount)}
                  </td>
                  <td style={{ padding: '10px 14px', textAlign: 'center' }}>
                    <span
                      style={{
                        padding: '3px 8px',
                        borderRadius: 6,
                        fontSize: 11,
                        fontWeight: 700,
                        backgroundColor: '#EFF6FF',
                        color: '#2563EB',
                        textTransform: 'uppercase',
                      }}
                    >
                      {job.output_format || 'PDF'}
                    </span>
                  </td>
                  <td style={{ padding: '10px 14px', textAlign: 'center' }}>
                    <span
                      style={{
                        padding: '3px 8px',
                        borderRadius: 12,
                        fontSize: 11,
                        fontWeight: 700,
                        backgroundColor: job.status === 'completed' ? '#D1FAE5' : '#FEE2E2',
                        color: job.status === 'completed' ? '#065F46' : '#991B1B',
                        textTransform: 'uppercase',
                      }}
                    >
                      {job.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    borderRadius: 14,
    borderWidth: 1,
    marginHorizontal: 20,
    marginTop: 14,
    marginBottom: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  topBar: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
  },
  refreshText: {
    fontSize: 12,
    fontWeight: '600',
  },
  loadingBox: {
    paddingVertical: 40,
    alignItems: 'center',
    gap: 10,
  },
  loadingText: {
    fontSize: 13,
  },
  emptyBox: {
    paddingVertical: 50,
    alignItems: 'center',
    gap: 8,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  emptyDesc: {
    fontSize: 13,
  },
});
